// TypeScript type definitions for AFYA application

// ============================================================================
// Prisma Entity Types
// ============================================================================

// Import Prisma generated types
// Note: These are generated by `prisma generate` and available after running that command
import type { User, Client, Packet } from '.prisma/client'
import type { Role, PacketType, PacketStatus } from '.prisma/client'

// Re-export for convenience
export type { User, Client, Packet, Role, PacketType, PacketStatus }

// ============================================================================
// API Request Types
// ============================================================================

/**
 * Request body for POST /api/intake/submit
 * Contains all fields from the comprehensive intake form
 */
export interface IntakeSubmitRequest {
  // Basic Information (Required)
  fullName: string;
  email: string;
  
  // Basic Information (Optional)
  gender?: string;
  dateOfBirth?: string;
  heightInches?: string;
  weightLbs?: string;
  
  // Activity & Goals
  activityLevel?: string;
  dailyMovementPattern?: string;
  mainFitnessGoals?: string;
  trainingExperience?: string;
  trainingHistory?: string;
  
  // Training Preferences
  daysPerWeek?: string;
  sessionDuration?: string;
  preferredWorkoutTime?: string;
  availableEquipment?: string;
  workoutLocation?: string;
  trainingStyle?: string;
  coachingStyle?: string;
  
  // Motivation & Challenges
  motivation?: string;
  biggestStruggle?: string;
  
  // Health & Medical
  injuries?: string;
  medicalConditions?: string;
  medications?: string;
  painOrDiscomfort?: string;
  
  // Nutrition
  dietType?: string;
  foodAllergies?: string;
  foodsToAvoid?: string;
  eatsBreakfast?: string;
  eatsAnimalProducts?: string;
  mealsPerDay?: string;
  beverageConsumption?: string;
  waterIntakeOz?: string;
  typicalDayEating?: string;
  favoriteMeals?: string;
  preferredMacros?: string;
  fastingPattern?: string;
  culturalDietaryNeeds?: string;
  
  // Program Delivery
  deliveryPreference?: string;
  wantsWeeklyCheckins?: string;
  
  // Sport-Specific (Optional)
  sportsPlayed?: string;
  schoolGrade?: string;
  eatsBeforePractice?: string;
  staysHydrated?: string;
  seasonMotivation?: string;
  seasonChallenges?: string;
}

/**
 * Request body for POST /api/packets/update (webhook)
 * Sent by Google Apps Script to update packet status
 */
export interface PacketUpdateRequest {
  clientEmail?: string;
  clientId?: string;
  packetType: 'INTRO' | 'NUTRITION' | 'WORKOUT';
  status: 'READY' | 'FAILED';
  docUrl?: string;
  error?: string;
}

// ============================================================================
// API Response Types
// ============================================================================

/**
 * Response from POST /api/intake/submit
 */
export interface IntakeSubmitResponse {
  success: boolean;
  client: {
    id: string;
    fullName: string;
    email: string;
  };
  packets: Array<{
    id: string;
    type: PacketType;
    status: PacketStatus;
  }>;
}

/**
 * Response from POST /api/packets/update
 */
export interface PacketUpdateResponse {
  success: boolean;
  packet?: {
    id: string;
    type: PacketType;
    status: PacketStatus;
    docUrl: string | null;
  };
  error?: string;
}

/**
 * Response from GET /api/me/client
 */
export interface ClientDataResponse {
  client: {
    id: string;
    fullName: string;
    email: string;
    goal: string | null;
    createdAt: string;
  };
  packets: Array<{
    id: string;
    type: PacketType;
    status: PacketStatus;
    docUrl: string | null;
    createdAt: string;
    updatedAt: string;
  }>;
}

/**
 * Generic error response structure
 */
export interface ErrorResponse {
  error: string;
  field?: string;
  code?: string;
}

// ============================================================================
// Form Data Types
// ============================================================================

/**
 * Form data structure for the intake form component
 * All fields are strings to match HTML form input values
 */
export interface IntakeFormData {
  // Basic Information
  fullName: string;
  email: string;
  gender: string;
  dateOfBirth: string;
  heightInches: string;
  weightLbs: string;
  
  // Activity & Goals
  activityLevel: string;
  dailyMovementPattern: string;
  mainFitnessGoals: string;
  trainingExperience: string;
  trainingHistory: string;
  
  // Training Preferences
  daysPerWeek: string;
  sessionDuration: string;
  preferredWorkoutTime: string;
  availableEquipment: string;
  workoutLocation: string;
  trainingStyle: string;
  coachingStyle: string;
  
  // Motivation & Challenges
  motivation: string;
  biggestStruggle: string;
  
  // Health & Medical
  injuries: string;
  medicalConditions: string;
  medications: string;
  painOrDiscomfort: string;
  
  // Nutrition
  dietType: string;
  foodAllergies: string;
  foodsToAvoid: string;
  eatsBreakfast: string;
  eatsAnimalProducts: string;
  mealsPerDay: string;
  beverageConsumption: string;
  waterIntakeOz: string;
  typicalDayEating: string;
  favoriteMeals: string;
  preferredMacros: string;
  fastingPattern: string;
  culturalDietaryNeeds: string;
  
  // Program Delivery
  deliveryPreference: string;
  wantsWeeklyCheckins: string;
  
  // Sport-Specific (Optional)
  sportsPlayed: string;
  schoolGrade: string;
  eatsBeforePractice: string;
  staysHydrated: string;
  seasonMotivation: string;
  seasonChallenges: string;
}

/**
 * Login form data (email-based authentication)
 */
export interface LoginFormData {
  email: string;
}

// ============================================================================
// Utility Types for Role-Based Access Control
// ============================================================================

/**
 * Type guard to check if a user has admin or coach role
 */
export type AdminRole = Extract<Role, 'ADMIN' | 'COACH'>;

/**
 * Type guard to check if a user has client role
 */
export type ClientRole = Extract<Role, 'CLIENT'>;

/**
 * Helper type for role-based permissions
 */
export interface RolePermissions {
  canAccessAdmin: boolean;
  canViewAllClients: boolean;
  canEditClients: boolean;
  canAccessDashboard: boolean;
}

/**
 * User session data with role information
 */
export interface UserSession {
  id: string;
  email: string;
  name?: string | null;
  role: Role;
}

/**
 * Extended client data with related entities
 */
export interface ClientWithPackets extends Client {
  packets: Packet[];
}

/**
 * Extended user data with client relationship
 */
export interface UserWithClient extends User {
  client: Client | null;
}

// ============================================================================
// Component Props Types
// ============================================================================

/**
 * Props for PacketCard component
 */
export interface PacketCardProps {
  packet: {
    id: string;
    type: PacketType;
    status: PacketStatus;
    docUrl: string | null;
    createdAt?: string | Date;
    updatedAt?: string | Date;
  };
}

/**
 * Props for ClientTable component
 */
export interface ClientTableProps {
  clients: Array<{
    id: string;
    fullName: string;
    email: string;
    createdAt: Date | string;
    _count?: {
      packets: number;
    };
  }>;
  onClientSelect?: (clientId: string) => void;
}

/**
 * Props for ClientDetail component
 */
export interface ClientDetailProps {
  client: {
    id: string;
    fullName: string;
    email: string;
    goal: string | null;
    createdAt: Date | string;
  };
  packets: Array<{
    id: string;
    type: PacketType;
    status: PacketStatus;
    docUrl: string | null;
    lastError: string | null;
    createdAt: Date | string;
    updatedAt: Date | string;
  }>;
}

/**
 * Props for IntakeForm component
 */
export interface IntakeFormProps {
  onSuccess: (data: IntakeSubmitResponse) => void;
  onError: (error: string) => void;
}

// ============================================================================
// Validation Types
// ============================================================================

/**
 * Form validation error structure
 */
export type FormErrors<T> = Partial<Record<keyof T, string>>;

/**
 * Validation result
 */
export interface ValidationResult {
  isValid: boolean;
  errors: Record<string, string>;
}

// ============================================================================
// Database Query Types
// ============================================================================

/**
 * Options for querying clients with filters
 */
export interface ClientQueryOptions {
  includePackets?: boolean;
  includeUser?: boolean;
  orderBy?: 'createdAt' | 'updatedAt' | 'fullName' | 'email';
  orderDirection?: 'asc' | 'desc';
}

/**
 * Options for querying packets with filters
 */
export interface PacketQueryOptions {
  clientId?: string;
  type?: PacketType;
  status?: PacketStatus;
  includeClient?: boolean;
}
